### ISSUE TITLE
ESDL to JSON to Julia graph structure

### ISSUE THREAD

**Issue by suvayu** [TulipaEnergy/TulipaIO.jl#1]
- [x] Convert ESDL to JSON using [`esdl2json`](https://github.com/TulipaEnergy/esdl2json) (based on code by @Lokkij)
- [x] Create the graph edges/flows
    - for posterity: TulipaEnergy/TulipaEnergyModel.jl#359
    - for current implementation, see: [`src/parsers.jl`](https://github.com/TulipaEnergy/TulipaIO.jl/blob/main/src/parsers.jl)
- [ ] Read other flow related attributes; ~see [`FlowData`](../blob/main/src/input-tables.jl#L39-L56)~
- [ ] Read flow profiles; ~see [`FlowProfiles`](../blob/main/src/input-tables.jl#L58-L67)~
  - [x] TulipaEnergy/TulipaIO.jl#6
    Every `ReferenceProfile` in an ESDL file has to be retrieved from InfluxDB.  There's no Julia client, so we wrote one.
- [ ] Combine the flow definitions with the profiles
   - The data structure that is used by the JuMP model is [`GraphFlowData`](../blob/main/src/structures.jl#L74-L114), which combines (3-4).
- [ ] Read assets with its attributes; see [`AssetData`](../blob/main/src/input-tables.jl#L1-L17), [`GraphAssetData`](../blob/main/src/structures.jl#L20-L72)

**Comment by suvayu** [comment]
@datejada @clizbe I found an instance where merging the attributes from the "from" and "to" nodes has conflicts (see the norse mythology file, also in the [repo](https://github.com/TulipaEnergy/TulipaIO.jl/tree/main/test/data/esdl)):
```
ERROR: DomainError with Following fields have conflicting values:
┌──────────────────┬────────────┬───────────────┐
│           fields │ Waste heat │ HeatPump_4b33 │
├──────────────────┼────────────┼───────────────┤
│ initial_capacity │      100.0 │          10.0 │
│  investment_cost │       14.0 │          16.0 │
│    variable_cost │        2.0 │          15.0 │
└──────────────────┴────────────┴───────────────┘
```
Is this realistic? Any thoughts how to resolve this kind of conflicts?

**Comment by suvayu** [comment]
| Tulipa                                    |  ESDL                                                       |
|---------------------------------------|-------------------------------------------------------|
| capacity (charge/discharge)  | maxDischargeRate and maxChargeRate |

@clizbe  I'm not sure I understand this entry from the table.  ESDL has two different rates, whereas Tulipa has one. How does that map?

**Comment by clizbe** [comment]
That's up for debate. We'll most likely change Tulipa to 2.

**Comment by clizbe** [comment]
> @datejada @clizbe I found an instance where merging the attributes from the "from" and "to" nodes has conflicts (see the norse mythology file, also in the [repo](https://github.com/TulipaEnergy/TulipaIO.jl/tree/main/test/data/esdl)):
> 
> ```
> ERROR: DomainError with Following fields have conflicting values:
> ┌──────────────────┬────────────┬───────────────┐
> │           fields │ Waste heat │ HeatPump_4b33 │
> ├──────────────────┼────────────┼───────────────┤
> │ initial_capacity │      100.0 │          10.0 │
> │  investment_cost │       14.0 │          16.0 │
> │    variable_cost │        2.0 │          15.0 │
> └──────────────────┴────────────┴───────────────┘
> ```
> 
> Is this realistic? Any thoughts how to resolve this kind of conflicts?

Ah this is just because I filled in random numbers. You guys said that was fine!
Is it just a value conflict that doesn't make sense?

**Comment by suvayu** [comment]
> Is it just a value conflict that doesn't make sense?

Yes. Basically the logic is:
- if for asset 1 it's missing and asset 2 is present, accept value set with asset 2
- if asset 1 and asset 2 has set the same value, accept it
- if both assets set the value but thwy aren't equal, error

This is mostly to be conservative yet reasonable. If the rubric above looks good, I'll just make the esdl file conformant and proceed.

**Comment by suvayu** [comment]
> We'll most likely change Tulipa to 2.
In that case, for now I'll just pick one, and implement the other one but leave it commented out.

**Comment by abelsiqueira** [comment]
Some comments on the ESDL/Tulipa compatibility were added here: https://github.com/TulipaEnergy/TulipaEnergyModel.jl/discussions/606

**Comment by clizbe** [comment]
Abandoned in favor of ESDL4Tulipa
