### ISSUE TITLE
BUG: Println fixes error

### ISSUE THREAD

**Issue by clizbe** [TulipaEnergy/TulipaIO.jl#15]
To produce:

Run this script WITH and WITHOUT the println.
```Julia
import DataFrames as DF
import DuckDB: DBInterface, DB

#%% Base Case
con = DBInterface.connect(DB) # in-memory DB

res = DBInterface.execute(con, "SELECT * FROM read_csv_auto('test/data/Norse/assets-data.csv', header=true, skip=1)")
println(res)

base_case_df = DF.DataFrame(res.tbl)
```

Without the println it should throw this error:
![image](https://github.com/TulipaEnergy/TulipaIO.jl/assets/11889283/b6cbad45-c831-4314-9f46-0d08f47bcd12)

Running the code line by line (regardless of println) also runs without error.

@abelsiqueira's theory is this is an async issue. The "println" gives the computer time to think.

### Bug report upstream
- duckdb/duckdb#11196

**Comment by clizbe** [comment]
Having fun fixing bugs on vacation? 🤭

**Comment by suvayu** [comment]
Not just that, have a look at
pipeline.jl, I think you'll like the new unified API (thanks to your
comment!), and the docstrings :⁠-⁠P

-- 
Suvayu

Open source is the future. It sets us free.
