### ISSUE TITLE
Tests for the InfluxDB client

### ISSUE THREAD

**Issue by suvayu** [TulipaEnergy/TulipaIO.jl#23]
> ... add a step in CI that starts an influxdb container with an endpoint and some data.

_Originally posted by @suvayu in https://github.com/TulipaEnergy/TulipaIO.jl/issues/19#issuecomment-2042634233_

- [ ] Implement a test that runs with EDR but is not included in CI
- [ ] Implement a step in CI that spins up an InfluxDB instance, populates with dummy data, and runs the above test against this instance

**Comment by wcoenraads** [comment]
I can - but frankly, I think my time would be better spent elsewhere for now. These tests will be useful when we get more code relying on this functionality, and it would enable better testing then. But for now, these tests are quite a lot of work to create for what is literally 40 lines of simple code. So I would prefer to defer this work until it becomes more relevant.

**Comment by suvayu** [comment]
@wcoenraads Do you think the first point is also a lot of effort?  I would say if we can address the first one, and leave the more complete approach for later, it is a lot better.

**Comment by clizbe** [comment]
@suvayu Is this still relevant or can I close it unplanned?

**Comment by suvayu** [comment]
Close as superseded by `esdl4tulipa`
