### ISSUE TITLE
Minimal read-only InfluxDB client using the REST API in Julia

### ISSUE THREAD

**Issue by suvayu** [TulipaEnergy/TulipaIO.jl#6]
Every `ReferenceProfile` in an ESDL file has to retrieved from InfluxDB. There's no Julia client, so we need to write one using the REST API (as recommended by the vendor).  The client should be minimal with only the features we need.  For now:
- [ ] Read `ReferenceProfile` from InfluxDB

**Comment by clizbe** [comment]
Closed by #19
